# Generated by Django 5.1.2 on 2024-12-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
